version: '3.9'
services:
  console:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Point to local API
        - VITE_API_URL=http://0.0.0.0:3000
        - NODE_ENV=production
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - console_network
networks:
  console_network:
    driver: bridge
