FROM node:20 AS build

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY ./ /app/

# Run these commands in downstream.

# ARG VITE_API_URL=${VITE_API_URL}
# RUN npm run build
# FROM nginx:1
# COPY --from=build /app/dist/ /usr/share/nginx/html
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# COPY ./nginx-backend-not-found.conf /etc/nginx/extra-conf.d/backend-not-found.conf
