version: 2
jobs:
  build-base-image:
    environment:
      IMAGE_NAME: eb129/incidentbot-console
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build base Docker Image
          command: |
            echo 'export IMAGE_TAG=$(cat version)' >> "$BASH_ENV"
            source "$BASH_ENV"
            docker build --file Dockerfile.base --tag $IMAGE_NAME:$IMAGE_TAG .
  publish-base-image:
    environment:
      IMAGE_NAME: eb129/incidentbot-console
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish base Docker Image to Docker Hub
          command: |
            echo 'export IMAGE_TAG=$(cat version)' >> "$BASH_ENV"
            source "$BASH_ENV"
            docker build --file Dockerfile.base --tag $IMAGE_NAME:$IMAGE_TAG .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$IMAGE_TAG
  helm:
    docker:
      - image: eb129/docker-kubectl:v1.2.0
    steps:
      - checkout
      - run: scripts/helm.sh
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - publish:
          filters:
            branches:
              only: main
      - helm:
          context: helm-charts-repository
