/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutMaintenanceImport } from './routes/_layout/maintenance'
import { Route as LayoutIncidentsIndexImport } from './routes/_layout/incidents/index'
import { Route as LayoutIncidentsIdImport } from './routes/_layout/incidents/$id'
import { Route as LayoutAdminUsersImport } from './routes/_layout/admin/users'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMaintenanceRoute = LayoutMaintenanceImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutIncidentsIndexRoute = LayoutIncidentsIndexImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutIncidentsIdRoute = LayoutIncidentsIdImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminUsersRoute = LayoutAdminUsersImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/maintenance': {
      id: '/_layout/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof LayoutMaintenanceImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/incidents/$id': {
      id: '/_layout/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof LayoutIncidentsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/incidents/': {
      id: '/_layout/incidents/'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof LayoutIncidentsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutMaintenanceRoute: typeof LayoutMaintenanceRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
  LayoutIncidentsIdRoute: typeof LayoutIncidentsIdRoute
  LayoutIncidentsIndexRoute: typeof LayoutIncidentsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutMaintenanceRoute: LayoutMaintenanceRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
  LayoutIncidentsIdRoute: LayoutIncidentsIdRoute,
  LayoutIncidentsIndexRoute: LayoutIncidentsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/maintenance': typeof LayoutMaintenanceRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/incidents/$id': typeof LayoutIncidentsIdRoute
  '/incidents': typeof LayoutIncidentsIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/maintenance': typeof LayoutMaintenanceRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/incidents/$id': typeof LayoutIncidentsIdRoute
  '/incidents': typeof LayoutIncidentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/maintenance': typeof LayoutMaintenanceRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/incidents/$id': typeof LayoutIncidentsIdRoute
  '/_layout/incidents/': typeof LayoutIncidentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/maintenance'
    | '/settings'
    | '/'
    | '/admin/users'
    | '/incidents/$id'
    | '/incidents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/maintenance'
    | '/settings'
    | '/'
    | '/admin/users'
    | '/incidents/$id'
    | '/incidents'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/maintenance'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/users'
    | '/_layout/incidents/$id'
    | '/_layout/incidents/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/maintenance",
        "/_layout/settings",
        "/_layout/",
        "/_layout/admin/users",
        "/_layout/incidents/$id",
        "/_layout/incidents/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/maintenance": {
      "filePath": "_layout/maintenance.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings": {
      "filePath": "_layout/settings.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/users": {
      "filePath": "_layout/admin/users.tsx",
      "parent": "/_layout"
    },
    "/_layout/incidents/$id": {
      "filePath": "_layout/incidents/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/incidents/": {
      "filePath": "_layout/incidents/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
